import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Card from '../components/Card'

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>WebApp Bercanda</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <nav className="flex w-full bg-blue-100 px-8 py-3 justify-between">
        <div>
          <span>logo</span>
        </div>
        <div>
          <a href="#">Home</a>
        </div>
      </nav>

      <main className="w-full">
        <div className="mx-10 my-10">
          <h2 className="font-bold text-xl mb-4">Buku</h2>
          <div className="flex flex-wrap w-full space-x-4">
            <Card title="Some title" author="author" />
            <Card title="Some title" author="author" />
          </div>
        </div>
        <div className="mx-10 my-10">
          <h2 className="font-bold text-xl mb-4">Penulis</h2>
          <div className="flex flex-wrap w-full space-x-4">
            <Card title="Nama Penulis" author="1 Buku" />
            <Card title="Nama Penulis" author="1 Buku" />
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
